### ISSUE TITLE
new label and milestones

### ISSUE THREAD

**Issue by kotzendekrabbe** [meetalva/alva#95]
Add Labels and Milestones that makes sence and are easy to understand
Labels will help contributers, maintainers and chore team to get a better overview - same for milestones

- [x] make label proposal
- [x] make milesontens proposal
- [x] add new labels
- [x] add new milestones
- [x] add new labels to issues
- [x] add new milestones to issues
- [x] document labels
